import { Member, Project, EventItem } from './types';

export const MEMBERS_DATA: Member[] = [
  // Position Holders (col-span-2 row-span-2)
  {
    id: 'm1',
    name: 'Shruti Gupta',
    role: 'The Secretary',
    category: 'executive',
    imageSeed: 'shruti',
    image: 'assests/Sample2.jpg',
    github: 'https://github.com',
    linkedin: 'https://linkedin.com',
    email: 'coordinator.webdesign@iitbbs.ac.in',
  },
  {
    id: 'm2',
    name: 'Prashant Sharma',
    role: 'Web Governor',
    category: 'executive',
    imageSeed: 'nisha_co_coordinator',
    image: 'assests/Sample2.jpg',
    github: 'https://github.com',
    linkedin: 'https://linkedin.com',
    email: 'cocoordinator.webdesign@iitbbs.ac.in',
  },
  {
    id: 'm3',
    name: 'Shriya Panda',
    role: 'Web and Design Governor',
    category: 'executive',
    imageSeed: 'sayan_web_lead',
    image: 'assests/Sample2.jpg',
    github: 'https://github.com',
    linkedin: 'https://linkedin.com',
    email: 'webdev.lead@iitbbs.ac.in',
  },
  {
    id: 'm4',
    name: 'K J S Rohit',
    role: 'Design Governor',
    category: 'executive',
    imageSeed: 'rohan_design_lead',
    image: 'assests/Sample2.jpg',
    github: 'https://github.com',
    linkedin: 'https://linkedin.com',
    email: 'creative.lead@iitbbs.ac.in',
  },
  // Core Members (col-span-1 row-span-1)
  {
    id: 'm5',
    name: 'Rajesh Mohanty',
    role: 'Dev Lead',
    category: 'core',
    imageSeed: 'pranav_core',
    image: 'assests/Sample2.jpg',
    github: 'https://github.com',
    linkedin: 'https://linkedin.com',
  },
  {
    id: 'm6',
    name: 'Priyanshu Dev Guru',
    role: 'Design Lead',
    category: 'core',
    imageSeed: 'kritika_core',
    image: 'assests/Sample2.jpg',
    github: 'https://github.com',
    linkedin: 'https://linkedin.com',
  },
  {
    id: 'm7',
    name: 'Aarush Mahawar',
    role: 'Management Lead',
    category: 'core',
    imageSeed: 'ananya_core',
    image: 'assests/Sample2.jpg',
    github: 'https://github.com',
    linkedin: 'https://linkedin.com',
  },
  {
    id: 'm8',
    name: 'Shantaneel Sarkar',
    role: 'Public Connection Lead',
    category: 'core',
    imageSeed: 'aditya_core',
    image: 'assests/Sample2.jpg',
    github: 'https://github.com',
    linkedin: 'https://linkedin.com',
  },
  // Alumni (Compact Row List)
  {
    id: 'm11',
    name: 'Biswajit Bhaiya',
    role: 'Former Coordinator (2024-25) • Now SDE at Stripe',
    category: 'alumni',
    imageSeed: 'siddharth_alumni',
    image: 'assests/Sample2.jpg',
    github: 'https://github.com',
    linkedin: 'https://linkedin.com',
  },
  {
    id: 'm12',
    name: 'Ashish Bhaiya',
    role: 'Former Web Lead (2024-25) • Product Designer at Razorpay',
    category: 'alumni',
    github: 'https://github.com',
    linkedin: 'https://linkedin.com',
    imageSeed: 'meghna_alumni',
    image: 'assests/Sample2.jpg',
  },
  {
    id: 'm13',
    name: 'Ayush Bhaiya',
    role: 'Former Web Developer (2023-24) • Graduate Student at CMU',
    category: 'alumni',
    github: 'https://github.com',
    linkedin: 'https://linkedin.com',
    imageSeed: 'tushar_alumni',
    image: 'assests/Sample2.jpg',
  }
];

export const PROJECTS_DATA: Project[] = [
  {
    id: 'p1',
    title: 'Academic Resource Portal',
    category: 'Full-Stack Development',
    year: '2025',
    summary: 'A unified platform for sharing and accessing academic resources.',
    description: 'A comprehensive academic hub designed to streamline the repository and retrieval of educational materials. It features advanced search algorithms, subject tagging, secure user uploads, and interactive discussion threads to facilitate seamless peer-to-peer knowledge sharing.',
    imageSeed: 'academia',
    tags: ['React', 'Node.js', 'Express', 'MongoDB', 'TailwindCSS'],
    github: 'https://github.com',
    demo: 'https://demo.com',
  },
  {
    id: 'p2',
    title: 'GoTogether',
    category: 'Real-time Collaboration',
    year: '2025',
    summary: 'A platform to find travel partners, share cabs, and divide costs.',
    description: 'A smart commuting and ride-matching platform built for campus residents. By clustering routes and schedules, GoTogether connects users traveling to similar locations, allowing them to coordinate bookings, share cabs, and equitably split transit expenses.',
    imageSeed: 'gotogether',
    tags: ['Next.js', 'Socket.io', 'Google Maps API', 'TailwindCSS', 'TypeScript'],
    github: 'https://github.com',
    demo: 'https://demo.com',
  },
  {
    id: 'p3',
    title: 'Campus Image Gallery',
    category: 'Media & Frontend Engineering',
    year: '2024',
    summary: 'A platform to view and showcase photoshoots and events happening on campus.',
    description: 'A high-performance media portfolio showcasing the vibrant culture and event photoshoots of the institute. Implemented with smooth animations, optimized image rendering, lazy loading, and gallery lightboxes for an immersive visual experience.',
    imageSeed: 'gallery',
    tags: ['React', 'Vite', 'Framer Motion', 'Cloudinary', 'TailwindCSS'],
    github: 'https://github.com',
  },
  {
    id: 'p4',
    title: 'Hostel Grievance Portal',
    category: 'Management Portal',
    year: '2025',
    summary: 'A portal for registering and tracking grievances related to hostels.',
    description: 'An automated dispute and maintenance tracking platform built to improve campus housing administration. Students can file issues under categories like plumbing, electricity, or Wi-Fi, monitor resolution status in real-time, and provide feedback directly to administrators.',
    imageSeed: 'grievance',
    tags: ['React', 'Node.js', 'Express', 'PostgreSQL', 'TailwindCSS'],
    github: 'https://github.com',
    demo: 'https://demo.com',
  },
  {
    id: 'p5',
    title: 'Certify',
    category: 'Automation Utilities',
    year: '2025',
    summary: 'A high-speed certificate generation engine creating customized certificates from templates and participant lists.',
    description: 'An automated credential generation system that helps event organizers programmatically draft and issue certificates in bulk. By mapping name lists to custom HTML/PDF templates, it processes thousands of files and emails them directly to recipients within minutes.',
    imageSeed: 'certify',
    tags: ['React', 'PDF-Lib', 'CSV Parser', 'NodeMailer', 'TypeScript'],
    github: 'https://github.com',
  },
  {
    id: 'p6',
    title: 'Vault Gymkhana',
    category: 'Inventory & Booking Portal',
    year: '2026',
    summary: 'A reservation portal for sports equipment issuing and court bookings.',
    description: 'A digital management system for Gymkhana resources. The portal features live equipment checkouts, automated overdue notifications, and a court booking system with conflict resolution to streamline athletic facilities administration.',
    imageSeed: 'vault',
    tags: ['Next.js', 'Prisma', 'PostgreSQL', 'TailwindCSS', 'Redis'],
    github: 'https://github.com',
    demo: 'https://demo.com',
  },
];

export const EVENTS_DATA: EventItem[] = [
  {
    id: 'e1',
    title: 'Frontend Battle',
    mode: 'online',
    participants: '6000+',
    rounds: 2,
    roundDetails: [
      'Round 1: Rapid UI layout implementation under specific constraints of custom asset packs, forced color themes, and restricted typography scales.',
      'Round 2: Rigorous engineering problems focusing on performance tuning, custom browser loops, accessible DOM structures, and complex state synchronization.'
    ],
    time: 'Mid - June',
    description: 'The ultimate frontend developer speedrun. Competitors go head-to-head to build high-performance web pages under strict visual constraints and optimize rendering pipelines under time-crunched situations.'
  },
  {
    id: 'e2',
    title: 'Design Dose',
    mode: 'online',
    participants: '1000+',
    focus: 'UI/UX problem solving & creative visualization',
    time: 'Early July',
    description: 'A curated virtual design marathon focusing on visual aesthetics and user experience architecture. Competitors solve real-world usability dilemmas and engineer high-fidelity creative layouts.'
  },
  {
    id: 'e3',
    title: 'Scope',
    mode: 'offline',
    focus: 'UI/UX & Frontend Development from absolute basics to advanced paradigms',
    time: 'Mid - September',
    description: 'A multi-day offline intensive bootcamp and workshop. Covers typography hierarchies, spatial grid layouts, responsive component design, and professional developer tools, turning ideas into production-ready web entities.'
  },
  {
    id: 'e4',
    title: 'Code Relay',
    mode: 'offline',
    participants: '4500+',
    rounds: 2,
    roundDetails: [
      'Round 1: Product idea validation, rapid wireframing, feature scoping, and system architecture pitch.',
      'Round 2: 24-hour sprint focusing on constructing, deploying, and presenting the fully functional product to a jury panel.'
    ],
    time: 'Late Feb / Early March',
    description: 'A team-based hackathon relay that brings developers and designers together. Teams coordinate closely to validate high-impact ideas and build complex, deployed products within tight deadlines.'
  }
];
