import { Member, Project, TimelineEvent } from './types';

export const MEMBERS_DATA: Member[] = [
  // Position Holders (col-span-2 row-span-2)
  {
    id: 'm1',
    name: 'Shruti Gupta',
    role: 'The Secretary',
    category: 'executive',
    imageSeed: 'shruti',
    image: 'assests/Sample2.jpg',
    github: 'https://github.com',
    linkedin: 'https://linkedin.com',
    email: 'coordinator.webdesign@iitbbs.ac.in',
  },
  {
    id: 'm2',
    name: 'Prashant Sharma',
    role: 'Web Governor',
    category: 'executive',
    imageSeed: 'nisha_co_coordinator',
    image: 'assests/Sample2.jpg',
    github: 'https://github.com',
    linkedin: 'https://linkedin.com',
    email: 'cocoordinator.webdesign@iitbbs.ac.in',
  },
  {
    id: 'm3',
    name: 'Shriya Panda',
    role: 'Web and Design Governor',
    category: 'executive',
    imageSeed: 'sayan_web_lead',
    image: 'assests/Sample2.jpg',
    github: 'https://github.com',
    linkedin: 'https://linkedin.com',
    email: 'webdev.lead@iitbbs.ac.in',
  },
  {
    id: 'm4',
    name: 'K J S Rohit',
    role: 'Design Governor',
    category: 'executive',
    imageSeed: 'rohan_design_lead',
    image: 'assests/Sample2.jpg',
    github: 'https://github.com',
    linkedin: 'https://linkedin.com',
    email: 'creative.lead@iitbbs.ac.in',
  },
  // Core Members (col-span-1 row-span-1)
  {
    id: 'm5',
    name: 'Rajesh Mohanty',
    role: 'Dev Lead',
    category: 'core',
    imageSeed: 'pranav_core',
    image: 'assests/Sample2.jpg',
    github: 'https://github.com',
    linkedin: 'https://linkedin.com',
  },
  {
    id: 'm6',
    name: 'Priyanshu Dev Guru',
    role: 'Design Lead',
    category: 'core',
    imageSeed: 'kritika_core',
    image: 'assests/Sample2.jpg',
    github: 'https://github.com',
    linkedin: 'https://linkedin.com',
  },
  {
    id: 'm7',
    name: 'Aarush Mahawar',
    role: 'Management Lead',
    category: 'core',
    imageSeed: 'ananya_core',
    image: 'assests/Sample2.jpg',
    github: 'https://github.com',
    linkedin: 'https://linkedin.com',
  },
  {
    id: 'm8',
    name: 'Shantaneel Sarkar',
    role: 'Public Connection Lead',
    category: 'core',
    imageSeed: 'aditya_core',
    image: 'assests/Sample2.jpg',
    github: 'https://github.com',
    linkedin: 'https://linkedin.com',
  },
  // Alumni (Compact Row List)
  {
    id: 'm11',
    name: 'Biswajit Bhaiya',
    role: 'Former Coordinator (2024-25) • Now SDE at Stripe',
    category: 'alumni',
    imageSeed: 'siddharth_alumni',
    image: 'assests/Sample2.jpg',
    github: 'https://github.com',
    linkedin: 'https://linkedin.com',
  },
  {
    id: 'm12',
    name: 'Ashish Bhaiya',
    role: 'Former Web Lead (2024-25) • Product Designer at Razorpay',
    category: 'alumni',
    github: 'https://github.com',
    linkedin: 'https://linkedin.com',
    imageSeed: 'meghna_alumni',
    image: 'assests/Sample2.jpg',
  },
  {
    id: 'm13',
    name: 'Ayush Bhaiya',
    role: 'Former Web Developer (2023-24) • Graduate Student at CMU',
    category: 'alumni',
    github: 'https://github.com',
    linkedin: 'https://linkedin.com',
    imageSeed: 'tushar_alumni',
    image: 'assests/Sample2.jpg',
  }
];

export const PROJECTS_DATA: Project[] = [
  {
    id: 'p1',
    title: 'IIT BBS Student Portal v2',
    category: 'Full-Stack Development',
    year: '2025',
    summary: 'A unified digital terminal streamlining academics, registrations, and hostel operations for 3000+ active campus students.',
    description: 'Developed from the ground up to replace legacy infrastructure, this portal implements real-time notifications, a custom schedule compiler, and role-based access controls. Built using a high-performance decoupled state manager, resulting in a 70% decrease in server load and absolute mobile responsiveness.',
    imageSeed: 'portal',
    tags: ['Next.js', 'React', 'TailwindCSS', 'PostgreSQL', 'Redis'],
    github: 'https://github.com',
    demo: 'https://demo.com',
  },
  {
    id: 'p2',
    title: 'Aura Interactive Exhibition',
    category: 'Creative Design & WebGL',
    year: '2025',
    summary: 'An immersive interactive art platform deploying spatial sound, WebGL shaders, and physics meshes for our annual tech-fest Alma Fiesta.',
    description: 'An experimental showcase utilizing custom GLSL vertex deformation shaders, vertex displacement systems, and spatial coordinates. Users explore a responsive virtual gallery where art pieces react to local cursor movements and mouse clicks.',
    imageSeed: 'aura',
    tags: ['WebGL', 'Three.js', 'GLSL Shaders', 'Web Audio API', 'React'],
    github: 'https://github.com',
    demo: 'https://demo.com',
  },
  {
    id: 'p3',
    title: 'Design System - Nebula',
    category: 'Design Engineering',
    year: '2024',
    summary: 'An open-source, highly customizable WCAG-compliant design language engineered for academic portals and institute publications.',
    description: 'Nebula is an opinionated design system providing accessible atomic components, complex bento-grid layouts, and responsive typographic scales. It includes built-in dark-mode parameters, keyboard navigability, and smooth CSS mask animations out of the box.',
    imageSeed: 'nebula',
    tags: ['Figma', 'Stitches', 'Radix Primitives', 'TailwindCSS', 'Storybook'],
    github: 'https://github.com',
  },
  {
    id: 'p4',
    title: 'Alma Fiesta Website v26',
    category: 'Web Development',
    year: '2026',
    summary: 'The official digital gateway for Central India’s premier socio-cultural festival, processing over 15,000 registrations.',
    description: 'Built as a high-fidelity visual experience featuring dynamic parallex timelines, particle-based loading states, and a custom gamified map navigation. Supported seamless payment gateways, QR code ticket generators, and an interactive schedule tracker.',
    imageSeed: 'almafiesta',
    tags: ['Vite', 'React', 'Framer Motion', 'TailwindCSS', 'Supabase'],
    github: 'https://github.com',
    demo: 'https://demo.com',
  },
  {
    id: 'p5',
    title: 'Cyber-Gold Identity Campaign',
    category: 'Motion & Visual Branding',
    year: '2025',
    summary: 'A complete brand overhaul and marketing visual engine defining the society’s digital identity through brutalist layouts.',
    description: 'Formulated a unified brand guidelines suite spanning geometric iconography, monochromatic off-black canvas spaces, and neon-yellow highlighting schemes. Delivered interactive motion assets, poster layout templates, and digital typography sheets.',
    imageSeed: 'cybergold',
    tags: ['After Effects', 'Illustrator', 'Figma', 'Brutalist Styling'],
    github: 'https://github.com',
  },
];

export const TIMELINE_DATA: TimelineEvent[] = [
  {
    year: '2021',
    title: 'Inception & Vision',
    description: 'The Web & Design Society was chartered with a core mission: to bridge the gap between academic theory and world-class digital craft at IIT Bhubaneswar.',
    details: 'Starting as a small interest group of 5 students, we set out to establish design guidelines and web development practices across multiple institute committees and student bodies.',
  },
  {
    year: '2022',
    title: 'Alma Fiesta Portal Debut',
    description: 'Engineered the first fully automated event registration system for the institute’s socio-cultural festival.',
    details: 'Implemented digital ticketing, dynamic scheduling, and live results portals, drastically reducing wait times and handling a peak traffic of 8,000 active concurrent connections successfully.',
  },
  {
    year: '2023',
    title: 'Nebula Design Language',
    description: 'Initiated the creation of the official open-source design token system for institutional websites.',
    details: 'Conducted campus-wide workshops on UI/UX principles, accessibility standards, and modern front-end tooling, growing our student community to over 200 passive learners.',
  },
  {
    year: '2024',
    title: 'Interactive WebGL Showcase',
    description: 'Pioneered WebGL and shader experimentation, moving from standard structural interfaces to canvas-driven artistic spaces.',
    details: 'Constructed custom shader systems for the tech festival. Our team members won several national hackathons representing IIT Bhubaneswar in creative web development.',
  },
  {
    year: '2025',
    title: 'Portal Modernization Program',
    description: 'Partnered with the institute administration to overhaul core internal academic and registration workflows.',
    details: 'Developed a modernized Student Portal v2 with decoupled server-side states and strict responsive views, which was adopted officially as the primary registration interface.',
  },
  {
    year: '2026',
    title: 'Immersive Digital Canvas',
    description: 'Unveiling our official Cyber-Gold showcase, proving that technical performance and extreme design aesthetics can coexist at 60 FPS.',
    details: 'This site stands as a testament to our continuous pursuit of engineering and design excellence, combining canvas loops, custom pixel dampeners, and elegant brutalist layouts.',
  }
];
